// netlify.toml
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Directory where your Netlify Functions are located
  directory = "netlify/functions"

[functions.chat]
  # Enable session affinity
  memory = 1024
  timeout = 10

[functions.auth]
  memory = 1024
  timeout = 10

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"